config/routes.rb
PolyDemo::Application.routes.draw do

  resources :ducks do
    resources :comments, defaults: {commentable: 'duck'}
  end

  resources :computers do
    resources :comments, defaults: {commentable: 'computer'}
  end

  resources :cars do
    resources :comments, defaults: {commentable: 'car'}
  end

end

app/models/computer.rb
class Computer < ActiveRecord::Base
  has_many :comments, as: :commentable
end

app/controllers/computers_controller.rb
class ComputersController < ApplicationController
  before_action :set_computer, only: [:show, :edit, :update, :destroy]

  # GET /computers
  # GET /computers.json
  def index
    @computers = Computer.all
  end

  # GET /computers/1
  # GET /computers/1.json
  def show
  end

  # GET /computers/new
  def new
    @computer = Computer.new
  end

  # GET /computers/1/edit
  def edit
  end

  # POST /computers
  # POST /computers.json
  def create
    @computer = Computer.new(computer_params)

    respond_to do |format|
      if @computer.save
        format.html { redirect_to @computer, notice: 'Computer was successfully created.' }
        format.json { render action: 'show', status: :created, location: @computer }
      else
        format.html { render action: 'new' }
        format.json { render json: @computer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /computers/1
  # PATCH/PUT /computers/1.json
  def update
    respond_to do |format|
      if @computer.update(computer_params)
        format.html { redirect_to @computer, notice: 'Computer was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @computer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /computers/1
  # DELETE /computers/1.json
  def destroy
    @computer.destroy
    respond_to do |format|
      format.html { redirect_to computers_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_computer
      @computer = Computer.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def computer_params
      params.require(:computer).permit(:make, :model, :price)
    end
end

app/helpers/computers_helper.rb
module ComputersHelper
end

app/views/computers/_form.html.erb
<%= form_for(@computer) do |f| %>
  <% if @computer.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@computer.errors.count, "error") %> prohibited this computer from being saved:</h2>

      <ul>
      <% @computer.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :make %><br>
    <%= f.text_area :make %>
  </div>
  <div class="field">
    <%= f.label :model %><br>
    <%= f.text_area :model %>
  </div>
  <div class="field">
    <%= f.label :price %><br>
    <%= f.text_field :price %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/computers/edit.html.erb
<h1>Editing computer</h1>

<%= render 'form' %>

<%= link_to 'Show', @computer %> |
<%= link_to 'Back', computers_path %>

app/views/computers/index.html.erb
<h1>Listing computers</h1>

<table>
  <thead>
    <tr>
      <th>Make</th>
      <th>Model</th>
      <th>Price</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @computers.each do |computer| %>
      <tr>
        <td><%= computer.make %></td>
        <td><%= computer.model %></td>
        <td><%= computer.price %></td>
        <td><%= link_to 'Show', computer %></td>
        <td><%= link_to 'Edit', edit_computer_path(computer) %></td>
        <td><%= link_to 'Destroy', computer, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Computer', new_computer_path %>

app/views/computers/new.html.erb
<h1>New computer</h1>

<%= render 'form' %>

<%= link_to 'Back', computers_path %>

app/views/computers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Make:</strong>
  <%= @computer.make %>
</p>

<p>
  <strong>Model:</strong>
  <%= @computer.model %>
</p>

<p>
  <strong>Price:</strong>
  <%= @computer.price %>
</p>

<%= link_to 'Edit', edit_computer_path(@computer) %> |
<%= link_to 'Back', computers_path %>