config/routes.rb
PolyDemo::Application.routes.draw do

  resources :ducks do
    resources :comments, defaults: {commentable: 'duck'}
  end

  resources :computers do
    resources :comments, defaults: {commentable: 'computer'}
  end

  resources :cars do
    resources :comments, defaults: {commentable: 'car'}
  end

end

app/models/duck.rb
class Duck < ActiveRecord::Base
  has_many :comments, as: :commentable
end

app/controllers/ducks_controller.rb
class DucksController < ApplicationController
  before_action :set_duck, only: [:show, :edit, :update, :destroy]

  # GET /ducks
  # GET /ducks.json
  def index
    @ducks = Duck.all
  end

  # GET /ducks/1
  # GET /ducks/1.json
  def show
  end

  # GET /ducks/new
  def new
    @duck = Duck.new
  end

  # GET /ducks/1/edit
  def edit
  end

  # POST /ducks
  # POST /ducks.json
  def create
    @duck = Duck.new(duck_params)

    respond_to do |format|
      if @duck.save
        format.html { redirect_to @duck, notice: 'Duck was successfully created.' }
        format.json { render action: 'show', status: :created, location: @duck }
      else
        format.html { render action: 'new' }
        format.json { render json: @duck.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /ducks/1
  # PATCH/PUT /ducks/1.json
  def update
    respond_to do |format|
      if @duck.update(duck_params)
        format.html { redirect_to @duck, notice: 'Duck was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @duck.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /ducks/1
  # DELETE /ducks/1.json
  def destroy
    @duck.destroy
    respond_to do |format|
      format.html { redirect_to ducks_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_duck
      @duck = Duck.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def duck_params
      params.require(:duck).permit(:name, :color, :sound, :backback)
    end
end

app/helpers/ducks_helper.rb
module DucksHelper
end

app/views/ducks/_form.html.erb
<%= form_for(@duck) do |f| %>
  <% if @duck.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@duck.errors.count, "error") %> prohibited this duck from being saved:</h2>

      <ul>
      <% @duck.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :color %><br>
    <%= f.text_field :color %>
  </div>
  <div class="field">
    <%= f.label :sound %><br>
    <%= f.text_field :sound %>
  </div>
  <div class="field">
    <%= f.label :backback %><br>
    <%= f.check_box :backback %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/ducks/edit.html.erb
<h1>Editing duck</h1>

<%= render 'form' %>

<%= link_to 'Show', @duck %> |
<%= link_to 'Back', ducks_path %>

app/views/ducks/index.html.erb
<h1>Listing ducks</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Color</th>
      <th>Sound</th>
      <th>Backback</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @ducks.each do |duck| %>
      <tr>
        <td><%= duck.name %></td>
        <td><%= duck.color %></td>
        <td><%= duck.sound %></td>
        <td><%= duck.backback %></td>
        <td><%= link_to 'Show', duck %></td>
        <td><%= link_to 'Edit', edit_duck_path(duck) %></td>
        <td><%= link_to 'Destroy', duck, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Duck', new_duck_path %>

app/views/ducks/new.html.erb
<h1>New duck</h1>

<%= render 'form' %>

<%= link_to 'Back', ducks_path %>

app/views/ducks/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @duck.name %>
</p>

<p>
  <strong>Color:</strong>
  <%= @duck.color %>
</p>

<p>
  <strong>Sound:</strong>
  <%= @duck.sound %>
</p>

<p>
  <strong>Backback:</strong>
  <%= @duck.backback %>
</p>

<%= link_to 'Edit', edit_duck_path(@duck) %> |
<%= link_to 'Back', ducks_path %>